name: reflutter
description: >
  A library to generate HTTP clients from metadata specified by users.
  The thought is that this can be used by Flutter based mobile apps to
  connect to their backend resources.
homepage: https://www.github.com/ctartamella/reflutter
version: 0.2.4
authors: 
  - Chris Tartamella <chris@tartamella.me>

environment:
  sdk: '>=2.0.0-dev.58.0 <2.0.0'

dependencies: 
  http: ^0.11.3
  meta: ^1.1.5
  analyzer: ^0.32.1
    
dev_dependencies:
  test: any