name: reflutter_test
description: >
  A library to generate HTTP clients from metadata specified by users.
  The thought is that this can be used by Flutter based mobile apps to
  connect to their backend resources.
homepage: https://www.github.com/ctartamella/reflutter
version: 0.5.2
authors: 
  - Chris Tartamella <chris@tartamella.me>

environment:
  sdk: '>=2.0.0-dev.63.0 <3.0.0'

dependencies: 
  http: ^0.12.0
  json_annotation: ^2.0.0
  reflutter: ^0.5.2
    
dev_dependencies:
  json_serializable: ^2.0.0
  build_runner: ^1.0.0
  test: any
  reflutter_generator: ^0.5.2

dependency_overrides:
  reflutter:
    path: ../reflutter
  reflutter_generator:
    path: ../reflutter_generator