name: reflutter_generator
description: >
  A library to generate HTTP clients from metadata specified by users.
  The thought is that this can be used by Flutter based mobile apps to
  connect to their backend resources.
homepage: https://www.github.com/ctartamella/reflutter
version: 0.5.2
author: Chris Tartamella <chris@tartamella.me>

environment:
  sdk: '>=2.0.0-dev.63.0 <3.0.0'

dependencies:
  meta: ^1.1.5
  analyzer: ^0.32.2
  build: ^1.0.1
  code_builder: ^3.1.1
  dart_style: ^1.1.1
  logging: ^0.11.3+1
  source_gen: ^0.9.0+1
  reflutter: ^0.5.2
  
dev_dependencies:
  build_runner: ^1.0.0

#dependency_overrides:
#  reflutter:
#    path: ../reflutter